name: CI
on:
  pull_request:
  push:
    branches:
      - develop
      - 'release/**'
  workflow_dispatch:

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - Env:${{ matrix.environment }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      JULIA_PKG_SERVER: ""
      JULIA_PROJECT: ${{ matrix.project-path }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1', 'nightly']
        os: [ubuntu-latest]
        arch: [x64]
        environment: ['standard', 'upstream']
        
        include:
          - environment: 'standard'
            project-path: 'RoME/test'
          - environment: 'upstream'
            project-path: 'RoME/test/upstream_test'
            
        exclude:
          - environment: 'upstream'
            julia-version: 'nightly'
            
    steps:
      - uses: actions/checkout@v6
      
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
          
      - uses: julia-actions/cache@v2
      
      # Julia automatically spins up in the folder specified by JULIA_PROJECT above.
      - name: Instantiate workspace
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.instantiate()
          
      - run: |
          git config --global user.name Tester
          git config --global user.email te@st.er

      - name: Run Test Suite
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.test("RoME"; coverage = true)
        continue-on-error: ${{ matrix.julia-version == 'nightly' }}
        
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: RoME/src,RoME/ext,RoMETypes/src
        if: ${{ matrix.julia-version == '1' }}
        
      - uses: codecov/codecov-action@v4
        if: ${{ matrix.julia-version == '1' }}
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
